### ISSUE TITLE
Money stolen from wallet

### ISSUE THREAD

**Issue by edieshow** [XMRWallet/Website#15]
Hello Admin,

I sent for your support. Answer me soon as possible. The site was down for a half hour, then i logged in to my wallet. It's fully cleaned and all my founds disappeared. My system is hardened and fully clean, so it was not a hack from my side. The seed is not stored on any devices.

**Comment by nathroy** [comment]
Hi edieshow,

There was a large phishing campaign being run on google ads at this time. They were impersonating the official site and draining the entire balance of wallets. I am very sorry you had this happen. Since then we have displayed a large message on our home page. Always verify you are using xmrwallet.com.
