### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by grcasanova** [XMRWallet/Website#16]
I had around $5 in monero, they got stolen by this website. It's a scam

**Comment by roadmap5** [comment]
xmrwallet exit scam,a lot of people  got scammed  during past days with original webpage xmrwallet.com. Beware it!

**Comment by nathroy** [comment]
Hi guys,

There was a large phishing campaign being run on google ads at this time. They were impersonating the official site and draining the entire balance of wallets. I am very sorry you had this happen. Since then we have displayed a large message on our home page. Always verify you are using xmrwallet.com.
