### ISSUE TITLE
XMRWallet Website is a scam - no response from support - $275 in Monero Lost

### ISSUE THREAD

**Issue by gene621** [XMRWallet/Website#20]
I logged into my wallet yesterday.... I then performed a transfer successfully....  As soon as that was completed, about 2 minutes later my balance showed zero as the remainder of my XMR was being transferred out in a transaction I did not perform (and was on 2/10 confirms).. No response from support....   My belief is they selectively scam and everything is fine until it's not and your money is gone and they keep the veneer of legitimacy just enough to earn trust..  If I had logged off immediately after my transfer I wouldn't have noticed the unauthorized phantom transaction that just randomly popped up right in front of me for at least several days.. 

(if the admin of the site reaches out, i'll update this post accordingly, however as far as i'm concerned this is scammy AF...)

**Comment by nathroy** [comment]
Hi gene621,

There was a large phishing campaign being run on google ads at this time. They were impersonating the official site and draining the entire balance of wallets. I am very sorry you had this happen. Since then we have displayed a large message on our home page. Always verify you are using xmrwallet.com.
